### ISSUE TITLE
위챗 QR 코드 이미지 에러

### ISSUE THREAD

**Issue by JWWon** [saanghyuk/rucy_landing#1]
보내주신 QR 코드 이미지가 안열리는 형식이에요 ㅠ

이 부분만 해결하면 랜딩페이지는 거의 제작 완료되는 상황이어서

빨리 보내주시면 금방 처리해드리겠습니당~

**Comment by saanghyuk** [comment]
2020년 1월 25일 (토) 오후 10:56, JiwoonWon <notifications@github.com>님이 작성:
